apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: taskhub
  labels:
    app: taskhub
    component: backend
spec:
  type: ClusterIP
  selector:
    app: taskhub
    component: backend
  ports:
    - port: 80
      targetPort: 5678
