apiVersion: v1
kind: Service
metadata:
  name: database-headless
  namespace: taskhub
  labels:
    app: taskhub
    component: database
spec:
  clusterIP: None
  selector:
    app: taskhub
    component: database
  ports:
    - port: 5432
      targetPort: 5432
